source 'https://rubygems.org'
gem 'sinatra'
gem 'thin'
gem 'sqlite3', github: 'larskanis/sqlite3-ruby', branch: 'add-gemspec'
gem 'rerun', github: 'alexch/rerun'
gem 'slim'
gem 'bcrypt'
gem 'sinatra-flash'
#gem 'byebug'
gem 'opencage-geocoder'
